[package]
name = "esdt-system-sc-meta"
version = "0.0.0"
authors = ["Runtime Verification"]
edition = "2021"
publish = false

[dependencies.esdt-system-sc]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.1"
