name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  container-name:
    description: 'Docker container name to use'
    required: true
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    shell: bash {0}
    env:
      CONTAINER_NAME: ${{ inputs.container-name }}
    run: |
      set -euxo pipefail

      TAG=runtimeverificationinc/${CONTAINER_NAME}

      USER=$(id -un)
      USER_ID=$(id -u)
      GROUP=$(id -gn)
      GROUP_ID=$(id -g)

      K_COMMIT=$(cat deps/k_release)

      docker build . --tag ${TAG}        \
        --build-arg K_COMMIT=${K_COMMIT} \
        --build-arg USER_ID=${USER_ID}   \
        --build-arg GROUP_ID=${GROUP_ID} \
        --build-arg USER=${USER}         \
        --build-arg GROUP=${GROUP}

      docker run                        \
        --name ${CONTAINER_NAME}        \
        --rm                            \
        --interactive                   \
        --tty                           \
        --detach                        \
        --user ${USER}:${GROUP}         \
        --workdir /home/${USER}         \
        -v "/etc/passwd:/etc/passwd:ro" \
        -v "/etc/group:/etc/group:ro"   \
        ${TAG}

      docker cp . ${CONTAINER_NAME}:/home/${USER}
      docker exec ${CONTAINER_NAME} chown -R ${USER}:${GROUP} /home/${USER}
