name: 'Update poetry for wasm-semantics'
on:
  push:
    branches:
      - '_update-deps/runtimeverification/wasm-semantics'
# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-submodule:
    name: 'Update poetry'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:    
          submodules: recursive
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
      - name: 'Configure GitHub user'
        run: |
          git config user.name devops
          git config user.email devops@runtimeverification.com
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Update wasm-semantics'
        run: |
          poetry -C kmultiversx update
          git add --update && git commit -m "Update poetry" || true
      - name: 'Push updates'
        run: git push
